In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split

# Load The dataset

In [2]:
data=pd.read_csv('insurance.csv')
data.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,50,57,176,29.90,False,Agra,Factory Worker,Medium
1,56,90,168,19.22,False,Allahabad,Businessman,Medium
2,26,87,178,36.95,False,Srinagar,Sales Manager,Low
3,34,73,162,14.75,False,Meerut,Banker,Low
4,43,47,192,19.32,True,Varanasi,Marketing Manager,High

In [3]:
data.describe()

               age      weight      height   income_lpa
count  4000.000000  4000.00000  4000.00000  4000.000000
mean     40.953750    71.96900   172.57175    25.896793
std      13.439504    16.13698    13.27258    13.946143
min      18.000000    45.00000   150.00000     2.010000
25%      29.000000    58.00000   161.00000    13.727500
50%      41.000000    72.00000   173.00000    25.600000
75%      52.000000    86.00000   184.00000    38.035000
max      64.000000    99.00000   195.00000    50.000000

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         4000 non-null   int64
 1   weight                      4000 non-null   int64
 2   height                      4000 non-null   int64
 3   income_lpa                  4000 non-null   float64
 4   smoker                      4000 non-null   bool
 5   city                        4000 non-null   str
 6   occupation                  4000 non-null   str
 7   insurance_premium_category  4000 non-null   str
dtypes: bool(1), float64(1), int64(3), str(3)
memory usage: 222.8 KB

In [5]:
dataset=pd.DataFrame(data)
dataset.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,50,57,176,29.90,False,Agra,Factory Worker,Medium
1,56,90,168,19.22,False,Allahabad,Businessman,Medium
2,26,87,178,36.95,False,Srinagar,Sales Manager,Low
3,34,73,162,14.75,False,Meerut,Banker,Low
4,43,47,192,19.32,True,Varanasi,Marketing Manager,High

In [ ]:
# Function that calculates BMI
def bmi(weight,height):
    """
    Provide this function wiht
    Height in meters
    Weight in Kgs

    It will return bmi 
    """
    bmi=round(weight/(height**2),2)
    return bmi